CREATE TABLE IF NOT EXISTS qiita_article_ids (
  id      INT(11)      NOT NULL AUTO_INCREMENT,
  item_id VARCHAR(255) NOT NULL COMMENT 'QiitaでのID',
  PRIMARY KEY (id),
  UNIQUE (item_id)
) ENGINE InnoDB AUTO_INCREMENT 1 DEFAULT CHARSET utf8mb4 DEFAULT COLLATE utf8mb4_bin COMMENT 'Qiitaの記事ID';
